/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'shansgup' at '7/19/16 4:26 PM' with Gradle 2.13
 *
 * @author shansgup, @date 7/19/16 4:26 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
